config/routes.rb
Rails.application.routes.draw do
  root "user#index"
  delete "logout", to: "sessions#destroy"

  get "password", to: "passwords#edit"
  patch "password", to: "passwords#update"

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"

  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  resources :articles, :user, :sessions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/ }, uniqueness: true
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    end
  end

  def require_user_logged_in!
    if Current.user.nil?
      redirect_to new_session_path, alert: "You have to log in firstly"
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index

  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index

  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new

  end

  def create
    @user = User.find_by(email: params[:email])

    if @user.present?
      PasswordMailer.with(user: @user).reset.deliver_later
    end

    redirect_to root_path

  end

  def edit
    @user = User.find_signed(params[:token], purpose: "password_reset")
  end

  def update
    @user = User.find_signed(params[:token], purpose: "password_reset")

    if @user.update(password_params)
      redirect_to new_session_path
    else
      render :edit
    end
  end

    private

    def password_params
      params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  before_action :require_user_logged_in!

  def edit

  end

  def update
    if Current.user.update(password_params)
      redirect_to root_path, notice: "password updated"
    else
      render :edit
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:email])

    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out"
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    if session[:user_id]
      @user = User.find(session[:user_id])
      # render partial: "user/showName"
    end

  end

  def show
    if session[:user_id]
      @user = User.find(session[:user_id])
    end
  end

  def new
    @user= User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :userName)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/articles/index.html.erb
<% @users.each do |user| %>
  <% if user %>
    <%= @user.userName %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MailerApp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<div class="container">
  <div class="">
    <nav class="m-2 p-0 navbar navbar-expand-lg navbar-light shadow-lg bg-white rounded">
      <div class="container-fluid">
        <a class="navbar-brand" href="<%=root_path %>"><h2>Mailer App</h2></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
          <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
            <li class="nav-item">
            </li>

          </ul>
          <div class="d-flex">

              <%= render "user/showName" %>

          </div>
        </div>
      </div>
    </nav>
    <div class="d-flex flex-column align-items-center">
      <div class="content w-75 border border-dark">
        <%= yield %>
      </div>
    </div>
  </div>

</div>

</body>
</html>

app/views/password_reset/edit.html.erb
password_reset

app/views/password_resets/edit.html.erb
<div class="d-flex flex-column align-items-center">
  <div class="mt-5 w-25 d-flex flex-column align-items-center ">

    <div class="mb-4">
      <h5>Reset your password</h5>
    </div>

    <%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |form| %>

      <div class="mb-3">
        <%= form.label :password %>
        <%= form.password_field :password, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, class: "form-control" %>
      </div>
      <div class="mb-3 text-center">
        <%= form.submit "Reset password", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>





<!--<div class="d-flex flex-column align-items-center">-->
<!--  <div class="mt-5 w-25 d-flex flex-column align-items-center">-->
<!--    <h2>Edit password</h2>-->
    <%#= form_with model: Current.user, url: password_path do |form| %>
      <%# if form.object.errors.any? %>
<!--        <div class="alert alert-danger">-->
          <%# form.object.errors.full_messages.each do |err| %>
<!--            <div>-->
              <%#= err %>
<!--            </div>-->
          <%# end %>
<!--        </div>-->
      <%# end %>

<!--      <div class="mb-3">-->
        <%#= form.label :password %>
        <%#= form.password_field :password, class: "form-control" %>
<!--      </div>-->

<!--      <div class="mb-3">-->
        <%#= form.label :password_confirmation %>
        <%#= form.password_field :password_confirmation, class: "form-control" %>
<!--      </div>-->

<!--      <div class="mb-3 text-center">-->
        <%#= form.submit "Update password", class: "btn btn-primary" %>
<!--      </div>-->
    <%# end %>
<!--  </div>-->
<!--</div>-->

app/views/password_resets/new.html.erb
<div class="d-flex flex-column align-items-center">
  <div class="mt-5 w-25 d-flex flex-column align-items-center ">

    <div class="mb-4">
      <h5>Forgot your password?</h5>
    </div>

    <%= form_with url: password_reset_path do |form| %>

      <div class="mb-3">
        <%= form.label :email %>
        <%= form.text_field :email, class: "form-control" %>
      </div>

      <div class="mb-3 text-center">
        <%= form.submit "Reset password", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/user/_showName.html.erb
<% if Current.user%>

  <a href="<%= user_path(Current.user.id) %>" class="m-1 btn btn-secondary" role="button"><%= Current.user.userName %></a>
  <a href="<%= logout_path %>" class="m-1 btn btn-danger" role="button" data-method="delete">Log out</a>

<% else %>

  <a href="<%= new_user_path %>" class="m-1 btn btn-primary" role="button">Sign up</a>
  <a href="<%= new_session_path %>" class="m-1 btn btn-white" role="button">Log in</a>

<% end %>

app/views/user/index.html.erb
user#index this is test_branchgit a

app/views/user/new.html.erb
<div class="d-flex flex-column align-items-center">
  <div class="w-25 d-flex flex-column align-items-center ">
    <h1>Sign in</h1>
    <%= form_with model: @user, url: user_index_path do |form| %>
      <% if @user.errors.any? %>
        <div class="alert alert-danger">
          <% @user.errors.full_messages.each do |err| %>
            <div>
              <%= err %>
            </div>
          <% end %>
        </div>
      <% end %>
      <div class="mb-3">
        <%= form.label :email %>
        <%= form.text_field :email, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :Name %>
        <%= form.text_field :userName, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :password %>
        <%= form.password_field :password, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, class: "form-control" %>
      </div>
      <div class="mb-3 text-center">
        <%= form.submit "Sign up", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/user/show.html.erb
<% if @user %>
  <p><%= @user.userName %></p>
  <p><%= @user.email %></p>
  <p><%= @user.id %></p>
  <p>edit ur password:</p>
  <%= link_to "Edit password", password_path %>
<% end %>